name: Feature Request
description: Suggest a new feature for the app
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! ✨

        We value your input and want to build features that truly benefit our users.

  - type: textarea
    id: feature-summary
    attributes:
      label: Feature Summary
      description: A clear and concise description of the feature you'd like to see
      placeholder: Summarize the feature in 1-2 sentences
    validations:
      required: true

  - type: textarea
    id: problem-statement
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? Who would benefit?
      placeholder: Describe the problem this feature would solve
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: Describe your ideal solution for this feature
      placeholder: How would you like this feature to work?
    validations:
      required: true

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Provide specific examples of how this feature would be used
      placeholder: |
        Example scenarios:
        - As a user, I want to...
        - When I'm..., I need to...
    validations:
      required: true

  - type: checkboxes
    id: health-considerations
    attributes:
      label: Health & Wellness Impact
      description: Check all that apply (for health-related features)
      options:
        - label: This feature involves health data collection
        - label: This feature affects data privacy/security
        - label: This feature requires medical accuracy
        - label: This feature impacts accessibility
        - label: This feature relates to user safety

  - type: checkboxes
    id: design-philosophy
    attributes:
      label: Nothing Design Philosophy
      description: Confirm alignment with our design principles
      options:
        - label: Feature aligns with minimalist design principles
        - label: Feature maintains clean, functional interface
        - label: Feature uses appropriate contrast and typography
        - label: Feature follows established interaction patterns

  - type: checkboxes
    id: platform
    attributes:
      label: Platform
      description: Which platforms should this feature support?
      options:
        - label: Android
        - label: Web (future)
        - label: Both

  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would improve user experience
        - High - Important for user satisfaction
        - Critical - Essential for app functionality
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Describe any alternative solutions or features you've considered
      placeholder: What other approaches might work?

  - type: textarea
    id: technical-considerations
    attributes:
      label: Technical Considerations
      description: Any technical requirements, dependencies, or constraints?
      placeholder: |
        - New libraries needed?
        - Performance implications?
        - Offline support required?
        - Integration requirements?

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other context, mockups, or examples about the feature request
      placeholder: Links to similar features, mockups, research, etc.

  - type: markdown
    attributes:
      value: |
        ---
        **Note**: Features involving health data will undergo additional review for accuracy, privacy, and regulatory compliance.
